### ISSUE TITLE
The Snap install does not work on Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by marqrdt** [klaussinani/tusk#171]
**Describe the bug**
Using "sudo snap install tusk" on Ubuntu 18.04.2 LTS does not produce an executable application. The AppImage works.

**To Reproduce**
Run: sudo snap install tusk
I've included how my system behaves after running the Snap install.
paul@myhost:~$ tusk
{ Error: Cannot find module '../screen'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/opt/Tusk/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.get [as screen] (/opt/Tusk/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at Win.get _screenDimensions [as _screenDimensions] (/opt/Tusk/resources/app.asar/src/win.js:12:38)
    at Win.get _minDimensions [as _minDimensions] (/opt/Tusk/resources/app.asar/src/win.js:33:40)
    at Win.get defaultOpts [as defaultOpts] (/opt/Tusk/resources/app.asar/src/win.js:38:35)
    at createMainWindow (/opt/Tusk/resources/app.asar/index.js:42:44) code: 'MODULE_NOT_FOUND' }
paul@myhost:~$ /snap/bin/tusk
## nothing happens here
paul@myhost:~$ ls -l /snap/bin/tusk
lrwxrwxrwx 1 root root 13 Mar  5 22:06 /snap/bin/tusk -> /usr/bin/snap
paul@myhost:~$ /usr/bin/tusk
bash: /usr/bin/tusk: No such file or directory

**Expected behavior**
The Tusk application should open.

**Technical Info (please complete the following information)**
 - OS: Ubuntu 18.04.2 LTS
 - Tusk Version:
paul@myhost:~$ snap list
Name                  Version          Rev   Tracking  Publisher        Notes
...
tusk                  0.22.0           28    stable    klaussinani      -

**Additional context**
I downloaded the AppImage from this GitHub site and it runs as expected!

**Comment by novdddd** [comment]
Work on Ubuntu 16 🤔

**Comment by senin24** [comment]
I have same problem at Ubuntu 18.04.2 LTS.
In Logs find only this:
apparmor_parser
AVC apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="snap-update-ns.tusk" pid=10225 comm="apparmor_parser"

**Comment by senin24** [comment]
works for me if install from deb-file:
```
sudo dpkg -i tusk_0.22.0_amd64.deb
sudo apt-get install -f
sudo dpkg -i tusk_0.22.0_amd64.deb
tusk
```

**Comment by akhileshsiddhanti** [comment]
Same issue!
